export const WORKER_URL = "https://wf-tool-proxy-worker.edelamf0.workers.dev/";

export const TIER_URLS = {
  Lith: "https://wiki.warframe.com/images/LithRelicIntact.png?ee7d7",
  Meso: "https://wiki.warframe.com/images/MesoRelicIntact.png?a9b4a",
  Neo: "https://wiki.warframe.com/images/NeoRelicIntact.png?6dc86",
  Axi: "https://wiki.warframe.com/images/AxiRelicIntact.png?6cadf",
  Requiem: "https://wiki.warframe.com/images/RequiemRelicIntact.png?03821",
};

export const WEAPON_SOURCES = [
  "https://cdn.jsdelivr.net/gh/WFCD/warframe-items@master/data/json/Primary.json",
  "https://cdn.jsdelivr.net/gh/WFCD/warframe-items@master/data/json/Secondary.json",
  "https://cdn.jsdelivr.net/gh/WFCD/warframe-items@master/data/json/Melee.json",
  "https://cdn.jsdelivr.net/gh/WFCD/warframe-items@master/data/json/Arch-Gun.json",
];
export const DROP_CHANCES = {
  Intact: { rare: 0.02, uncommon: 0.22, common: 0.76 },
  Exceptional: { rare: 0.04, uncommon: 0.26, common: 0.7 },
  Flawless: { rare: 0.06, uncommon: 0.34, common: 0.6 },
  Rad: { rare: 0.1, uncommon: 0.4, common: 0.5 },
};
export const RIVEN_STATS = [
  { slug: "critical_chance", name_en: "Crit Chance", name_es: "Prob. Crítica" },
  { slug: "critical_damage", name_en: "Crit Damage", name_es: "Daño Crítico" },
  { slug: "multishot", name_en: "Multishot", name_es: "Multidisparo" },
  {
    slug: "base_damage_/_melee_damage",
    name_en: "Damage",
    name_es: "Daño Base",
  },
  {
    slug: "fire_rate_/_attack_speed",
    name_en: "Fire Rate / Attack Speed",
    name_es: "Cadencia / Vel. Ataque",
  },
  { slug: "status_chance", name_en: "Status Chance", name_es: "Prob. Estado" },
  { slug: "toxin_damage", name_en: "Toxin", name_es: "Toxina" },
  { slug: "heat_damage", name_en: "Heat", name_es: "Calor" },
  { slug: "electric_damage", name_en: "Electric", name_es: "Electricidad" },
  { slug: "cold_damage", name_en: "Cold", name_es: "Frío" },
  { slug: "weapon_recoil", name_en: "Recoil", name_es: "Retroceso" },
  { slug: "range", name_en: "Range", name_es: "Alcance" },
  { slug: "magazine_capacity", name_en: "Magazine Cap", name_es: "Cargador" },
  { slug: "reload_speed", name_en: "Reload Speed", name_es: "Vel. Recarga" },
  {
    slug: "damage_vs_grineer",
    name_en: "Dmg Grineer",
    name_es: "Daño Grineer",
  },
  { slug: "damage_vs_corpus", name_en: "Dmg Corpus", name_es: "Daño Corpus" },
  {
    slug: "damage_vs_infested",
    name_en: "Dmg Infested",
    name_es: "Daño Infestado",
  },
];

export const TEXTS = {
  es: {
    inventory: {
      title: "Mi Inventario",
      empty: "Inventario vacío. Usa el escáner.",
      searchPlaceholder: "Filtrar (Ej: G1)...",
      sort: {
        recent: "Recientes",
        valIntact: "Valor (Intacta)",
        valRad: "Valor (Radiante)",
        ducats: "Ducados",
      },
      actions: {
        clear: "Borrar Todo",
        deleteConfirm: "¿Seguro que quieres borrar todo el inventario?",
      },
    },
    ocr: {
      cameraTitle: "Escáner de Reliquias",
      btnCapture: "Capturar",
      btnUpload: "Subir Foto",
      btnSave: "GUARDAR EN INVENTARIO",
      guide: "Apunta a la lista de reliquias",
      analyzing: "Analizando imagen...",
      results: "Resultados Detectados",
      noText: "No se detectó texto claro. Intenta acercarte.",
      success: "Guardado correctamente.",
    },
    lfgPresets: {
      title: "Mensajes Guardados",
      btnSave: "GUARDAR PRESET",
      placeholder: "Nombre (ej: Eidolon 5x3)",
      empty: "No hay presets guardados.",
      deleteConfirm: "¿Borrar este preset?",
    },
    modes: {
      capture: "Captura",
      extermination: "Exterminio",
      exterminate: "Exterminio",
      rescue: "Rescate",
      sabotage: "Sabotaje",
      "void cascade": "Cascada del Vacío",
      "void flood": "Inundación del Vacío",
      "void armageddon": "Armagedón del Vacío",
      disruption: "Interrupción",
      survival: "Supervivencia",
      defense: "Defensa",
      mobile_defense: "Defensa Móvil",
      assault: "Asalto",
      hijack: "Secuestro",
      spy: "Espionaje",
    },
    sync: {
      title: "Sincronización en la Nube",
      btnSend: "ENVIAR",
      btnReceive: " RECIBIR",
      lblCode: "Tu Código:",
      lblInput: "Introduce el código del otro dispositivo:",
      btnActionSend: "Enviar Portapapeles",
      waiting: "Esperando conexión...",
      success: "¡Recibido con éxito!",
      sending: "Enviando...",
      sent: "¡Enviado!",
      error: "Error. Intenta de nuevo.",
      limits: " Límite: 1000 syncs/día (Global). Los códigos expiran en 120s.",
      helpTooltip:
        "Usa esto para pasar textos (LFG, Compras) del Móvil al PC/Consola sin escribir.",
      placeholder: "Ej: 1234",
    },
    manualAdd: "Añadir al Inventario",
    addGuide:
      "ℹ️ Dos formas de añadir: Manualmente (botón +) o Escáner (Cámara). Las fotos se procesan 100% local en tu dispositivo.",
    lblProfit: "Rentabilidad (Media)",
    lblProfitSolo: "Rentabilidad (Solo)",
    lblProfitSquad: "Rentabilidad ({n} Jugadores)",
    lblRecommended: "⚡ Fisuras Recomendadas:",
    menuRelic: "Reliquia",
    menuSet: "Set",
    menuRiven: "Riven",
    menuProfile: "Perfil",
    menuLfg: "LFG",
    lblRelic: "Nombre de Reliquia",
    phRelic: "Ej: Lith A1...",
    lblItem: "Buscar Item (Ej: Xaku)",
    phItem: "Ej: Xaku, Protea...",
    lblRef: "Refinamiento",
    lblMiss: "Faltan",
    btnCopy: "Copiar Mensaje",
    btnPrice: "💲 Precio",
    msgCopied: "¡COPIADO!",
    noStock: "Sin datos",
    countMsg: "items",
    defaultRelic: "RELIQUIA",
    errLoad: "Error de conexión.",
    errFetch: "Error de red.",
    common: "Común",
    uncommon: "Poco Común",
    rare: "Raro",
    setInfo: "Set Completo",
    notFound: "No encontrado en Reliquias.",
    active: "ACTIVA",
    vaulted: "VAULTED",
    aya: "AYA (Varzia)",
    lblRivenW: "Arma del Riven",
    phRivenW: "Ej: Bramma, Nikana...",
    lblRivenS: "Estadísticas (Opcional)",
    headerTitle: "VOIDSTONKS",
    headerSub: "Optimización de Farm y Reclutamiento",
    lblProfit: "Rentabilidad (Media)",
    lblContent: "Contenido:",
    footerData: "Datos provistos por:",
    contactLabel: "¿Tienes ideas para mejorar la app?",
    contactLink: "w/Parcialsobriedad",
    rivenSearch: "🔎 BUSCAR PRECIO",
    refs: {
      rad: "Radiante",
      intact: "Intact",
      flawless: "Perfecta",
      exceptional: "Excepcional",
    },
    rarityAbbr: { common: "C", uncommon: "PC", rare: "R" },
    trackerTitle: "Progreso del Set",
    markDone: "✅ Ya lo tengo",
    markUndo: "Desmarcar",
    lblUser: "Nombre de Usuario (PC)",
    btnCheck: "Check",
    lblDailyFocus: "Foco Diario",
    lblStanding: "Reputación Restante",
    lblTraces: "Max Vestigios",
    disclaimer:
      "VoidStonks no está afiliado, respaldado ni patrocinado por Digital Extremes Ltd.Warframe™ es una marca registrada de Digital Extremes Ltd.",
    lblRelicFor: "Reliquias para: ",
    lblRivenNeg: "- Negativa (Opcional)",
    lblMrCalc: "Si la API falla, calcula por MR:",
    lblLfgActivity: "Actividad",
    lblLfgPlayers: "Jugadores Necesarios",
    tooltips: {
      netra:
        "Requiere: Rango 5 con Cavia. Misión de alta dificultad. 5 intentos semanales.",
      temporal:
        "Requiere: Historia principal , completar 1999. Serie de 3 misiones consecutivas en Höllvania sin pausas. Alta dificultad.",
      tabRelic: "Buscar contenidos y precios de Reliquias.",
      tabSet: "Ver precios de Sets completos y partes buscar.",
      tabRiven: "Precios y estadísticas de Mods Riven.",
      tabProfile: "Verificar maestría y cap de usuario.",
      tabLfg: "Generar mensajes de reclutamiento.",
      refinement:
        "Gasta Vestigios para aumentar la chance de recompensas Raras (Doradas).",
      omnia:
        "Requiere: Acceso a misiones de Cascada del Vacío o Conjunción. Permiten abrir CUALQUIER tipo de reliquia (Lith, Meso, Neo, Axi) al mismo tiempo (excepto Requiem).",
      steelPath:
        "Requiere: Completar todos los nodos del Mapa Estelar. Los enemigos tienen +100% de nivel, vida y armadura, pero obtienes +100% de probabilidad de recursos y Esencia de Acero.",
      vs: "Void Strike (Madurai). Esencial para romper escudos rápido.",
      dps: "Damage Dealer. Rompe las partes del Eidolon.",
      lure: "Encargado de mantener vivos los Señuelos.",
      volt: "Escudos Eléctricos para daño crítico.",
      harrow: "Protección contra picos de energía.",
      wisp: "Buffs de velocidad y vida.",
      profit:
        "Requiere: Rango 5 (Viejo Amigo) con Solaris United. Jefe 'araña' en Valles del Orbe. Meta principal: Farm de Créditos.",
      eda: "Requiere: Rango 5 con Cavia (Sanctum Anatomica). La misión más difícil del juego. Restricciones de equipo aleatorias a cambio de recompensas Élite.",
      archon:
        "Requiere: Aventura 'La Nueva Guerra'. Caza semanal de jefes. Recompensa: Fragmentos de Arconte (Mejoras permanentes de stats).",
      sortie:
        "Requiere: Aventura 'La Guerra Interna'. 3 misiones diarias con modificadores. Recompensa: Rivens, Endo, Piña Ayatan.",
      arbi: "Requiere: Completar TODOS los nodos del Mapa Solar. Misiones infinitas sin revivir. Meta: Endo y Mods Galvanizados.",
      radshare: "Todos usan Reliquia RADIANTE (100 vestigios).",
      intshare: "Todos usan Reliquia INTACTA (0 vestigios).",
      rotation: "Capturas de Hidrolista por ciclo nocturno.",
      meta: "Estrategia más eficiente/óptima.",
      casual: "Juego tranquilo sin requisitos estrictos.",
    },
    lfgOpts: {
      radshare: "Radshare",
      radshareInfo: "ℹ️ ¿Qué es Radshare?",
      eidolon: "Caza de Eidolon",
      profit: "Robaganancias",
      eda: "Archimedia Profunda",
      netra: "Netra-Celdas",
      archon: "Cacería de Arconte",
      sortie: "Incursión",
      arbi: "Arbitramento",
      temporal: "Archimedia Temporal",
    },
    lfgRoles: {
      dps: "DPS",
      lure: "Señuelos",
      volt: "Volt",
      wisp: "Wisp",
      harrow: "Harrow",
      meta: "Meta",
      casual: "Casual",
      elite: "Élite",
      run3x3: "3x3",
      run5x3: "5x3",
      run6x3: "6x3",
    },
  },
  en: {
    inventory: {
      title: "My Inventory",
      empty: "Inventory empty. Use scanner.",
      searchPlaceholder: "Filter (e.g. G1)...",
      sort: {
        recent: "Recent",
        valIntact: "Value (Intact)",
        valRad: "Value (Radiant)",
        ducats: "Ducats",
      },
      actions: {
        clear: "Clear All",
        deleteConfirm: "Are you sure you want to delete all?",
      },
    },
    ocr: {
      cameraTitle: "Relic Scanner",
      btnCapture: "Capture",
      btnUpload: "Upload File",
      btnSave: "SAVE TO INVENTORY",
      guide: "Aim at relic list",
      analyzing: "Analyzing image...",
      results: "Detected Results",
      noText: "No clear text detected. Try closer.",
      success: "Saved successfully.",
    },
    lfgPresets: {
      title: "Saved Presets",
      btnSave: "SAVE PRESET",
      placeholder: "Name (e.g., Eidolon 5x3)",
      empty: "No saved presets.",
      deleteConfirm: "Delete this preset?",
    },
    sync: {
      title: "Cloud Sync",
      btnSend: "📤 SEND",
      btnReceive: "📥 RECEIVE",
      lblCode: "Your Code:",
      lblInput: "Enter code from other device:",
      btnActionSend: "Send Clipboard",
      waiting: "Waiting for connection...",
      success: "Received successfully!",
      sending: "Sending...",
      sent: "Sent!",
      error: "Error. Try again.",
      limits: "⚠️ Limit: 1000 syncs/day (Global). Codes expire in 60s.",
      helpTooltip:
        "Use this to transfer text (LFG, Market) from Mobile to PC/Console instantly.",
      placeholder: "Ex: 1234",
    },
    modes: {
      capture: "Capture",
      extermination: "Exterminate",
      exterminate: "Exterminate",
      rescue: "Rescue",
      sabotage: "Sabotage",
      "void cascade": "Void Cascade",
      "void flood": "Void Flood",
      "void armageddon": "Void Armageddon",
      disruption: "Disruption",
      survival: "Survival",
      defense: "Defense",
      mobile_defense: "Mobile Defense",
      spy: "Spy",
    },
    manualAdd: "Add relic to Inventory",
    addGuide:
      "ℹTwo ways to adD relics: Manually press the add relic to inventory when you select a relic  or Scanner (Camera). Images are processed 100% locally on your device.",
    lblProfit: "Profitability (Avg)",
    lblProfitSolo: "Profitability (Solo)",
    lblProfitSquad: "Profitability ({n} Players)",
    lblRecommended: "⚡ Recommended Fissures:",
    menuRelic: "Relic",
    menuSet: "Set",
    menuRiven: "Riven",
    menuProfile: "Profile",
    menuLfg: "LFG",
    lblRelic: "Relic Name",
    phRelic: "e.g. Lith A1...",
    lblItem: "Search Item (e.g. Xaku)",
    phItem: "e.g. Xaku, Protea...",
    lblRef: "Refinement",
    lblMiss: "Need",
    btnCopy: "Copy Message",
    btnPrice: "💲 Price",
    msgCopied: "COPIED!",
    noStock: "No Data",
    countMsg: "items",
    defaultRelic: "RELIC",
    errLoad: "Connection Error.",
    errFetch: "Network Error.",
    common: "Common",
    uncommon: "Uncommon",
    rare: "Rare",
    setInfo: "Full Set",
    notFound: "Not found.",
    active: "ACTIVE",
    vaulted: "VAULTED",
    aya: "AYA (Varzia)",
    lblRivenW: "Riven Weapon",
    phRivenW: "e.g. Bramma...",
    lblRivenS: "Stats (Optional)",
    headerTitle: "VOIDSTONKS",
    headerSub: "Farm & Recruit Tool",
    lblProfit: "Profitability (Avg)",
    lblContent: "Contents:",
    footerData: "Data by:",
    contactLabel: "Ideas? PM me ingame or through wf forums",
    contactLink: "w/Parcialsobriedad",
    rivenSearch: "🔎 CHECK PRICE",
    refs: {
      rad: "Radiant",
      intact: "Intact",
      flawless: "Flawless",
      exceptional: "Exceptional",
    },
    rarityAbbr: { common: "C", uncommon: "UC", rare: "R" },
    trackerTitle: "Set Progress",
    markDone: "✅ Got it",
    markUndo: "Unmark",
    lblUser: "Username (PC)",
    btnCheck: "Check",
    lblDailyFocus: "Daily Focus",
    lblStanding: "Daily Standing",
    lblTraces: "Max Traces",
    disclaimer:
      "VoidStonks is not affiliated, endorsed, or sponsored by Digital Extremes Ltd.Warframe™ is a registered trademark of Digital Extremes Ltd.",
    lblRelicFor: "Relics for: ",
    lblRivenNeg: "- Negative (Optional)",
    lblMrCalc: "Calc by MR:",
    lblLfgActivity: "Activity",
    lblLfgPlayers: "Players Needed",
    tooltips: {
      temporal:
        "Requires: Complete 1999 quest , progressing main story. 3 consecutive missions in Höllvania with no breaks. High difficulty.",
      tabRelic: "Check Relic contents and prices.",
      tabSet: "Check Full Sets and parts prices.",
      tabRiven: "Riven Mods prices and stats.",
      tabProfile: "Check User Mastery and Caps.",
      tabLfg: "Generate recruiting messages.",
      refinement: "Spend Traces to boost Rare (Gold) drop chance.",
      omnia:
        "Requires: Access to Void Cascade or Conjunction Survival missions. They allow you to open ANY relic type (Lith, Meso, Neo, Axi) at the same time (except Requiem).",
      steelPath:
        "Requires: Clearing every node on the Star Chart. Enemies have +100% level, health, and armor, but you get +100% resource drop chance and Steel Essence.",
      vs: "Void Strike (Madurai). Breaks shields instantly.",
      dps: "Damage Dealer. Breaks limbs.",
      lure: "Lure Handler (Keeps lures alive).",
      volt: "Electric Shields for crit damage.",
      harrow: "Protection from energy spikes.",
      wisp: "Fire rate and health buffs.",
      profit:
        "Requires: Rank 5 (Old Mate) with Solaris United. 'Spider' boss in Orb Vallis. Main Goal: Massive Credit farm.",
      eda: "Requires: Rank 5 with Cavia (Sanctum). Hardest content in the game. Random loadout restrictions for Elite rewards.",
      archon:
        "Requires: 'The New War' quest. Weekly boss hunt. Reward: Archon Shards (Permanent stat boosts).",
      sortie:
        "Requires: 'The War Within' quest. Daily 3-mission chain. Reward: Rivens, Endo, Sculptures.",
      arbi: "Requires: Clearing ALL Star Chart nodes. Endless permadeath missions. Goal: Endo and Galvanized Mods.",
      radshare: "Everyone equips RADIANT relic.",
      intshare: "Everyone equips INTACT relic.",
      rotation: "Hydrolyst captures per night cycle.",
      meta: "Most efficient strategy.",
      casual: "Relaxed gameplay.",
    },
    lfgOpts: {
      radshare: "Radshare",
      radshareInfo: "ℹ️ What is Radshare?",
      eidolon: "Eidolon Hunt",
      profit: "Profit Taker",
      eda: "Deep Archimedea",
      archon: "Archon Hunt",
      netra: "Netracells",
      sortie: "Sortie",
      arbi: "Arbitration",
      netra: "Netracells",
      temporal: "Temporal Archimedea",
    },
    lfgRoles: {
      dps: "DPS",
      lure: "Lure",
      volt: "Volt",
      wisp: "Wisp",
      harrow: "Harrow",
      meta: "Meta",
      casual: "Casual",
      elite: "Elite",
      run3x3: "3x3",
      run5x3: "5x3",
      run6x3: "6x3",
    },
  },
};
